### ISSUE TITLE
Set item of Sub Form in a Customizing Table

### ISSUE THREAD

**Issue by ShannonCodeur** [a2lix/Demo#14]
Hi The Team !!! 
Hello everyone, I'm really stuck and I need your help. Indeed, I use this bundle and I manage to add and remove the elements following the demo. I would like to know if it is possible to customize the display of the form so that I can have a table where I would have more space on my page. Please. I'm not really doing well in jQuery. This is what i want 
![form](https://user-images.githubusercontent.com/36988296/74556542-91365a80-4f5e-11ea-8264-5b851b86e570.JPG)

and this is what i have now (Template)

![homologation](https://user-images.githubusercontent.com/36988296/74556703-eecaa700-4f5e-11ea-96ff-df9413dde4da.JPG)

**Comment by webda2l** [comment]
Not the right place sorry, you need to upgrade your knowledge about Twig (https://symfony.com/doc/current/form/form_customization.html, https://twig.symfony.com/doc/3.x/templates.html) and CSS.
