### ISSUE TITLE
Unable to find the association target class of "translations" in App\Entity\Category.

### ISSUE THREAD

**Issue by bepabg** [a2lix/Demo#18]
I try to test Demo with Symfony 5.0.7 but after call company/new I received that error:
Unable to find the association target class of "translations" in App\Entity\Category.

**Comment by webda2l** [comment]
Yes temporary problem from https://github.com/KnpLabs/DoctrineBehaviors/pull/544
Currently fixed by https://github.com/a2lix/Demo/commit/3cc541e895f246e4573e1b1aad6dd8447dfd940d
